import {
    blackColor,
    boxShadow,
    boxShadowLight,
    defaultFont,
    hexToRgb,
    whiteColor,
} from '../../sharedSportEraStyles.jss';
import image from '../../../img/peter-osmenda-20K-JZ2ppbE-unsplash.jpg';

const categoriesStyles = {
    container: {
        minHeight: 'calc(100vh - 9.0625rem)',
        height: 'auto',
        width: '100vw',
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
        margin: '0',
        padding: '0.5rem 0',
        background: `url(${image})`,
        backgroundAttachment: 'fixed',
        backgroundSize: 'cover',
        backgroundRepeat: 'no-repeat',
        backgroundPosition: 'center center',
    },
    titleWrapper: {
        position: 'relative',
        margin: '1rem 0',
        filter: 'drop-shadow(-1px 6px 3px rgba(50, 50, 0, 0.5))',
    },
    title: {
        ...defaultFont,
        padding: '0.5rem 1rem',
        fontSize: '1.10rem',
        textTransform: 'uppercase',
        fontWeight: '700',
        textAlign: 'center',
        color: `rgba(${hexToRgb(blackColor)}, 0.5)`,
        background: `linear-gradient(90deg, rgba(${hexToRgb(whiteColor)}, 0.8) 10%, 
                                            rgba(${hexToRgb(whiteColor)}, 0) 10%, 
                                            rgba(${hexToRgb(whiteColor)}, 0) 11%, 
                                            rgba(${hexToRgb(whiteColor)}, 0.8) 11%,
                                            rgba(${hexToRgb(whiteColor)}, 0.8) 12%,
                                            rgba(${hexToRgb(whiteColor)}, 0) 12%,
                                            rgba(${hexToRgb(whiteColor)}, 0) 13%,
                                            rgba(${hexToRgb(whiteColor)}, 0.8) 13%,
                                            rgba(${hexToRgb(whiteColor)}, 0.5) 30%,
                                            rgba(${hexToRgb(whiteColor)}, 0.5) 70%,
                                            rgba(${hexToRgb(whiteColor)}, 0.8) 87%,
                                            rgba(${hexToRgb(whiteColor)}, 0) 87%, 
                                            rgba(${hexToRgb(whiteColor)}, 0) 88%, 
                                            rgba(${hexToRgb(whiteColor)}, 0.8) 88%,
                                            rgba(${hexToRgb(whiteColor)}, 0.8) 89%,
                                            rgba(${hexToRgb(whiteColor)}, 0) 89%,
                                            rgba(${hexToRgb(whiteColor)}, 0) 90%,
                                            rgba(${hexToRgb(whiteColor)}, 0.8) 90%
                                    )`,
        mixBlendMode: 'multiply',
        '@media (min-width: 992px)': {
            fontSize: '1.5rem',
        },
        '@media (min-width: 1200px)': {
            fontSize: '3rem',
            marginBottom: '2.75rem',
            padding: '0',
        },
    },
    group: {
        margin: '0 0.5rem',
        '@media (min-width: 1200px)': {
            margin: '0 4rem',
        },
    },
    imageContainer: {
        height: 'auto',
        padding: '0.3rem',
        position: 'relative',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'flex-end',
        '&:hover': {
            transform: 'scale(0.95)',
            transition: '0.2s ease',
        },
        '@media (min-width: 1200px)': {
            padding: '0.5rem',
        },
    },
    image: {
        ...boxShadow,
        height: '30vh',
        width: '100%',
        objectFit: 'cover',
        '@media (min-width: 1200px)': {
            height: '50vh',
        },
    },
    categoryTitleContainer: {
        position: 'relative',
        display: 'flex',
        height: '100%',
        top: '0',
        left: '0',
        alignItems: 'flex-end',
        background: `rgba(${hexToRgb(whiteColor)}, 0.5)`,
    },
    categoryTitle: {
        ...defaultFont,
        ...boxShadowLight,
        display: 'inline-block',
        position: 'absolute',
        fontSize: '2rem',
        fontWeight: '600',
        color: `rgba(${hexToRgb(blackColor)}, 0.4)`,
        textTransform: 'uppercase',
        transformOrigin: 'bottom left 0',
        transform: 'translateY(34%) rotate(-90deg)',
        textAlign: 'center',
        width: '30vh',
        background: `rgba(${hexToRgb(whiteColor)}, 0.7)`,
        '@media (min-width: 1200px)': {
            width: '50vh',
            fontSize: '4rem',
            transform: 'translateY(16%) rotate(-90deg)',
        },
    },
    shade: {
        position: 'absolute',
        top: '0',
        left: '0',
        bottom: '0',
        right: '0',
        margin: '0.3rem',
        background: `rgba(${hexToRgb(whiteColor)}, 0.3)`,
        '@media (min-width: 1200px)': {
            margin: '0.5rem',
        },
    },
};

export default categoriesStyles;
